# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89cdc81e511a654230f414786b6b8180954bf146c58ba52bccce78bbcfe12b46bf9d715c6855407e099abe64244021c51cace4ea3eb0cc2f778646fb0ed1a604

test:
  secret_key_base: 186e8b6a11191c146170f903f9c1d14634ef76414fc21193806dc11d8c50a78bb8dfbc39c1787d27cab0231399aa086bf744d349b8b2980fb88c7784d3e6f2d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
